import Head from 'next/head'
import Header from '../components/Header'

const Home = () => {
  return (
    <>
      <Head>
        <title>Silesian Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </>
  )
}

export default Home